### ISSUE TITLE
Fragment transition issue

### ISSUE THREAD

**Issue by msureshmewara** [dandar3/android-support-annotations#1]
public final LayoutInflater getLayoutInflater() {
        return (LayoutInflater) this.getActivity().getSystemService(Context.LAYOUT_INFLATER_SERVICE);
    }

**Above function is giving error:**
'getLayoutInflater()' cannot override getLayoutInflater() in android.support.v4.app.Fragment: overridden method is final

After updating to buildToolVersion 27.0.3

**Comment by dandar3** [comment]
Are you extending a fragment and overriding getLayoutInflater()? Why not use the one already provided?

- [https://developer.android.com/reference/android/app/Fragment.html#getLayoutInflater()](https://developer.android.com/reference/android/app/Fragment.html#getLayoutInflater())
- [https://developer.android.com/reference/android/support/v4/app/Fragment.html#getLayoutInflater()](https://developer.android.com/reference/android/support/v4/app/Fragment.html#getLayoutInflater())

They both seem to be declared as final now - if I were you I would use the support Fragment and it's layout inflater.

Or if you really want you own implementation, define with a different name, as in:

```
public final LayoutInflater getSystemLayoutInflater() {
  return (LayoutInflater) this.getActivity().getSystemService(Context.LAYOUT_INFLATER_SERVICE);
}
```

**Comment by msureshmewara** [comment]
Thanks @dandar3 but i am getting error:

```
UncaughtException
java.lang.IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first.
 at android.view.ViewGroup.addViewInner(ViewGroup.java:4937)
 at android.view.ViewGroup.addView(ViewGroup.java:4768)
 at android.view.ViewGroup.addView(ViewGroup.java:4708)
 at android.view.ViewGroup.addView(ViewGroup.java:4681)
 at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1425)
 at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1750)
 at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1819)
 at android.support.v4.app.BackStackRecord.executePopOps(BackStackRecord.java:855)
 at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2587)
 at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2377)
 at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2332)
 at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2239)
 at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:700)
 at android.os.Handler.handleCallback(Handler.java:790)
 at android.os.Handler.dispatchMessage(Handler.java:99)
 at android.os.Looper.loop(Looper.java:164)
 at android.app.ActivityThread.main(ActivityThread.java:6494)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
```

**Comment by dandar3** [comment]
@mssureshmewara Can you give me some context as to when does it happen / what do you do as a user? maybe a bit of code excerpt.

**Comment by msureshmewara** [comment]
public abstract class BaseFragment extends Fragment {
    private static final String TAG = BaseFragment.class.getSimpleName();
.
.
@Override
    public void onAttach(Activity activity) {
        super.onAttach(activity);
}
.
.

.
private final KeyBackPressCallBack mKeyBackPressCallBack = new KeyBackPressCallBack() {
        @Override
        public void handleBackPress() {
            if (isFragmentValid()) {
                onKeyBackPress();
            }
        }
    };
.
.
@Override
    public final View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {
        if (this.mViewContainer != null && this.mViewContainer.getParent() != null) {
            ((ViewGroup) this.mViewContainer.getParent()).removeView(this.mViewContainer);
     }
}
.
.
 /*public final LayoutInflater getLayoutInflater() {
        return (LayoutInflater) this.getActivity().getSystemService(Context.LAYOUT_INFLATER_SERVICE);
    }*/
    public final LayoutInflater getSystemLayoutInflater() {
        return (LayoutInflater) this.getActivity().getSystemService(Context.LAYOUT_INFLATER_SERVICE);
    }
..
public static void replaceView(View currentView, View newView, ViewGroup.LayoutParams layoutParams) {
        ViewGroup parent = getParent(currentView);
        if (parent == null) {
            return;
        }
        final int index = parent.indexOfChild(currentView);
        removeView(currentView);
        removeView(newView);
        if (layoutParams != null) {
            parent.addView(newView, index, layoutParams);
        } else {
            parent.addView(newView, index);
        }
    }
protected abstract View onCreateContentView(LayoutInflater pInflater, ViewGroup pContainer);

    protected View onCreateFooterView(LayoutInflater pInflater, ViewGroup pContainer) {
        return null;
    }

    protected abstract void onCreateFragment(View pContentView);

    protected View onCreateHeaderView(LayoutInflater pInflater, ViewGroup pContainer) {
        return null;
    }

    public final View safeInflater(LayoutInflater pInflater, ViewGroup pContainer, int pLayoutResId) {
        return this.safeInflater(pInflater, pContainer, pLayoutResId, false);
    }

    public final View safeInflater(LayoutInflater pInflater, ViewGroup pContainer, int pLayoutResId, boolean pAttachToRoot) {
        View view = null;
        try {
            view = pInflater.inflate(pLayoutResId, pContainer, pAttachToRoot);
        } catch (Throwable e) {
            e.printStackTrace();
        }
        return view;
    }
.
.
protected void onKeyBackPress() {
        finishFragment();
    }

    public BaseActivity getBaseActivity() {
        return mActivity;
    }
/**
     * Replace fragment
     */
    public void replaceFragment(int pLayoutResId, Class<? extends BaseFragment> pFragment) {
        this.replaceFragment(pLayoutResId, pFragment, null, ANIMATION_RIGHT_IN_LEFT_OUT);
    }

    /**
     * Replace fragment
     */
    public void replaceFragment(int pLayoutResId, Class<? extends BaseFragment> pFragment, Bundle pBundle) {
        this.replaceFragment(pLayoutResId, pFragment, pBundle, ANIMATION_RIGHT_IN_LEFT_OUT);
    }

    /**
     * Replace fragment
     */
    public void replaceFragmentNoAnimation(int pLayoutResId, Class<? extends BaseFragment> pFragment, Bundle pBundle) {
        this.replaceFragment(pLayoutResId, pFragment, pBundle, 0);
    }

    /**
     * Replace fragment with custom animation
     */
    public void replaceFragment(int pLayoutResId, Class<? extends BaseFragment> pFragment, Bundle pBundle, int pAnimation) {
        this.replaceFragment(pLayoutResId, pFragment, pFragment.getName(), pBundle, getFragmentManager(), pAnimation);
    }

    /**
     * Replace fragment with custom animation
     */
    public void replaceFragment(int pLayoutResId, Class<? extends BaseFragment> pFragment, Bundle pBundle, int pAnimation, boolean isStateLossAccepted) {
        this.replaceFragment(pLayoutResId, pFragment, pFragment.getName(), pBundle, getFragmentManager(), pAnimation, isStateLossAccepted);
    }

    public void clearBackStack(FragmentManager pFragmentManager) {
        pFragmentManager.popBackStackImmediate(null, FragmentManager.POP_BACK_STACK_INCLUSIVE);
    }

    public void clearBackStackAndKeepFirstFragment(FragmentManager pFragmentManager) {
        //http://stackoverflow.com/questions/5802141/is-this-the-right-way-to-clean-up-fragment-back-stack-when-leaving-a-deeply-nest
        if (pFragmentManager.getBackStackEntryCount() > 0) {
            int firstFragmentId = pFragmentManager.getBackStackEntryAt(0).getId();
            pFragmentManager.popBackStackImmediate(firstFragmentId, 0);
        }
    }

    /**
     * Replace fragment with custom animation
     *
     * @param pLayoutResId
     * @param pFragment
     * @param pBundle
     * @param pFragmentManager
     * @param pAnimation
     */
    public void replaceFragment(int pLayoutResId, Class<? extends BaseFragment> pFragment, String pTag, Bundle pBundle, FragmentManager pFragmentManager, int pAnimation) {
        try {
            final BaseFragment frag = pFragment.newInstance();
            this.replaceFragment(pLayoutResId, frag, pTag, pBundle, pFragmentManager, pAnimation);
        } catch (Throwable e) {
            e.printStackTrace();
        }
    }
    /**
     * Replace fragment with custom animation
     *
     * @param pLayoutResId
     * @param pFragment
     * @param pBundle
     * @param pFragmentManager
     * @param pAnimation
     * @param isStateLossAccepted
     */
    public void replaceFragment(int pLayoutResId, Class<? extends BaseFragment> pFragment, String pTag, Bundle pBundle, FragmentManager pFragmentManager, int pAnimation, boolean isStateLossAccepted) {
        try {
            final BaseFragment frag = pFragment.newInstance();
            this.replaceFragment(pLayoutResId, frag, pTag, pBundle, pFragmentManager, pAnimation, isStateLossAccepted);
        } catch (Throwable e) {
            e.printStackTrace();
        }
    }

    public void replaceFragment(int pLayoutResId, BaseFragment pFragment, Bundle pBundle, FragmentManager pFragmentManager, int pAnimation) {
        try {
            this.replaceFragment(pLayoutResId, pFragment, pFragment.getTag(), pBundle, pFragmentManager, pAnimation);
        } catch (Throwable e) {
            e.printStackTrace();
        }
    }

    public void replaceFragment(int pLayoutResId, BaseFragment pFragment, int pAnimation) {
        this.replaceFragment(pLayoutResId, pFragment, null, null, getFragmentManager(), pAnimation);
    }

    private void replaceFragment(int pLayoutResId, BaseFragment pFragment, String pTag, Bundle pBundle, FragmentManager pFragmentManager, int pAnimation) {
        replaceFragment(pLayoutResId, pFragment, pTag, pBundle, pFragmentManager, pAnimation, false);
    }

    private void replaceFragment(int pLayoutResId, BaseFragment pFragment, String pTag, Bundle pBundle, FragmentManager pFragmentManager, int pAnimation, boolean isStateLossAccepted) {
        final FragmentTransaction fragmentTransaction = pFragmentManager.beginTransaction();
        switch (pAnimation) {
            case ANIMATION_BOTTOM_IN_TOP_OUT:
//                    fragmentTransaction.setCustomAnimations(R.animator.animator_bottom_in, R.animator.animator_top_out, R.animator.animator_top_in, R.animator.animator_bottom_out);
                fragmentTransaction.setCustomAnimations(R.anim.anim_bottom_in, R.anim.anim_top_out, R.anim.anim_top_in, R.anim.anim_bottom_out);
                break;
            case ANIMATION_RIGHT_IN_LEFT_OUT:
//                    fragmentTransaction.setCustomAnimations(R.animator.animator_right_in, R.animator.animator_left_out, R.animator.animator_left_in, R.animator.animator_right_out);
                fragmentTransaction.setCustomAnimations(R.anim.anim_right_in, R.anim.anim_left_out, R.anim.anim_left_in, R.anim.anim_right_out);
                break;
            case ANIMATION_SCALE_IN_RIGHT_OUT:
//                    fragmentTransaction.setCustomAnimations(R.animator.animator_scalex_enter, R.animator.animator_scalex_exit, R.animator.animator_left_in, R.animator.animator_right_out);
                fragmentTransaction.setCustomAnimations(R.anim.anim_scalex_enter, R.anim.anim_scalex_exit, R.anim.anim_left_in, R.anim.anim_right_out);
                break;
            case ANIMATION_ONLY_APPLY_REVERSE:
//                    fragmentTransaction.setCustomAnimations(R.animator.animator_none, R.animator.animator_none, R.animator.animator_left_in, R.animator.animator_right_out);
                fragmentTransaction.setCustomAnimations(R.anim.anim_none, R.anim.anim_none, R.anim.anim_left_in, R.anim.anim_right_out);
                break;
            default: // No animation
                break;
        }
        if (pBundle != null) {
            pFragment.setArguments(pBundle);
        }
        pFragment.setPreviousFragment(this);
        final String backStateName = pTag != null ? pTag : pFragment.getClass().getName();
        fragmentTransaction.addToBackStack(backStateName);
        fragmentTransaction.replace(pLayoutResId, pFragment, backStateName);
        if (isStateLossAccepted)
            fragmentTransaction.commitAllowingStateLoss();
        else
            fragmentTransaction.commit();
    }

    /**
     * Handle on fragment animation started
     */
    protected void onAnimationStarted() {
        runQueue();
    }

    /**
     * Handle on fragment animation ended
     */
    protected void onAnimationEnded() {
        runQueue();
    }

    /**
     * Handle on fragment animation repeated
     */
    protected void onAnimationRepeated() {
    }

    @Override
    public Animation onCreateAnimation(int transit, boolean enter, int nextAnim) {
        Animation animation = super.onCreateAnimation(transit, enter, nextAnim);
        if (animation == null) {
//            //If not, and an animation is defined, load it now
            if (nextAnim != 0) {
                animation = AnimationUtils.loadAnimation(mActivity, nextAnim);
            }
            //If there is an animation for this fragment, add a listener.
            if (animation != null) {
                animation.setAnimationListener(animationListener);
            } else {
                mIsAnimationEnd = true;
            }
        }
        if (animation != null) {
            // NOTE: the animation must be added to an animation set in order for the listener
            // to work on the exit animation
            final AnimationSet animSet = new AnimationSet(true);
            animSet.addAnimation(animation);
            return animSet;
        } else {
            // called animation end to setup view
            onAnimationEnded();
        }
        return null;
    }

    public final Animation.AnimationListener animationListener = new Animation.AnimationListener() {
        @Override
        public void onAnimationStart(Animation animation) {
            LogUtils.d("onAnimationStarted");
            onAnimationStarted();
            mIsAnimationEnd = false;
        }

        @Override
        public void onAnimationEnd(Animation animation) {
            LogUtils.d("onAnimationEnd");
            onAnimationEnded();
            mIsAnimationEnd = true;
        }

        @Override
        public void onAnimationRepeat(Animation animation) {
            onAnimationRepeated();
        }
    };
   public void finishFragment() {
        int backStackCount = getFragmentManager().getBackStackEntryCount();
        if (backStackCount > 0) {
            LogUtils.d(TAG, "popping back stack");
            getFragmentManager().popBackStack();
            if (backStackCount == 1) {
                finishActivity();
            }
        } else {
            LogUtils.d(TAG, "nothing on back stack, calling super");
//            mActivity.onBackPressed();
            finishActivity();
        }
    }

**Comment by dandar3** [comment]
@mssureshmewara 
Might be easier if you could create a simplified but runnable version of your application containing this code that you can upload into your Github account, then I could replicate what you see and we can take it from there.

**Comment by msureshmewara** [comment]
Thanks for your support.

This is done i changed getLayoutInflator() to getSupportFrament().

Thanks.

**Comment by dandar3** [comment]
Good to know how you solved it, thanks for telling.

BTW: Android Support Library 27.1.0 release is in the works, if you haven't done this already you can star [android-support-library-README](https://github.com/dandar3/android-support-library-README) project to keep an eye on it.
